### ISSUE TITLE
Velocyto does not work on cluster

### ISSUE THREAD

**Issue by linwang6** [velocyto-team/velocyto.py#126] opened 2018-10-02 04:11 UTC
Hi guys,

I have tested and tried Velocyto many times on cluster, and Velocyto does not work on cluster,  if you are using the qsub to submit the job to the cluster, please be noted this. Thanks.

**Comment by slinnarsson** [comment] 2018-10-02 04:17
Can you please be more specific about what you did and how it failed? 

We run velocyto every day on a cluster, but we don't use qsub. Most likely you have a configuration issue specific to qsub or your cluster, and you will have to ask the cluster administrator to help you get up and running.

**Comment by linwang6** [comment] 2018-10-02 04:30
Hi slinnarsson,
I using qsub to submit one bash file to the cluster, for example

Submit_velocyto.sh:

#!/bin/env bash
/home/xy6/anaconda3/bin/velocyto run -o /data/xy6/cellranger/test -@ 16 --samtools-memory 2000 -b /data/xy6/cellranger/test/barcodes.tsv -m /data/xy6/cellranger/hg38_repeats_repeatMasker_allTracks.gtf /data/xy6/cellranger/test
/test.bam /data/xy6/cellranger/genes.gtf

Is there anything I missed? Could you give a example how to set the configuration? How do you guys run it on cluster without using the qsub? You means only the cluster administrator have the privilege to run it? Thanks.

**Comment by mschilli87** [comment] 2018-10-02 06:32
duplicate of https://github.com/velocyto-team/velocyto.py/issues/123 & https://github.com/velocyto-team/velocyto.py/issues/124

**Comment by slinnarsson** [comment] 2018-10-02 06:33
:-) ok I'm closing this as it seems we're not getting anywhere, and it's not likely to be an issue with velocyto itself.

**Closed by slinnarsson** 2018-10-02 06:33 UTC

**Comment by linwang6** [comment] 2018-10-02 06:38
Hi slinnarsson,
I have no idea how to submit the velocyto on cluster, could you give one example and configuration file? Thanks.

**Comment by slinnarsson** [comment] 2018-10-02 06:45
No, sorry. We can advise how to run velocyto itself, but submitting jobs to a cluster is outside the scope. Every cluster is different, and you’ll just have to work with the cluster administrators to resolve your issues. 

You’ll have to make sure that your python installation is accessible from the compute nodes, that environment variables are set properly, that you have proper access permissions to the relevant directories, that each process is run from the correct directory etc. these are issues that are highly specific to your setup and we cannot help resolve them.
