### ISSUE TITLE
Does Velocyto work on cluster??

### ISSUE THREAD

**Issue by linwang6** [velocyto-team/velocyto.py#124] opened 2018-09-24 23:06 UTC
The Velocyto works locally, but when using qsub to submit the job to cluster, it does not work. Any guys run it successfully on cluster? Thanks.

**Comment by mschilli87** [comment] 2018-09-25 06:44
duplicate of https://github.com/velocyto-team/velocyto.py/issues/123

**Comment by linwang6** [comment] 2018-09-25 07:30
So weird, there was no anything output and no memory and cpu cost. And there was no errors output.

**Comment by gioelelm** [comment] 2018-09-25 07:33
Hi linwang6,

I am afraid I cannot help so much here. It seems a issue specific to your
systems configurations.

Are you using conda on the cluster?

**Comment by linwang6** [comment] 2018-09-25 07:49
I am not using the conda on the cluster. You mean the specific issue to the cluster's systems configuration? Velocyto works locally, but not works when submitted by using qsub.

**Comment by gioelelm** [comment] 2018-09-25 07:54
Yes exactly. Because of the dependencies on numpy, scipy, cython and a
cythonized module that needs to be compiled, many problems might arise if
any of them is not working 100%. The use of conda guarantees that you have
a working installation comparable to the one I was using when developing
the library.

**Comment by linwang6** [comment] 2018-09-25 22:34
Hi gioelelm,

When I try 'conda install numpy scipy cython numba matplotlib scikit-learn h5py click', it gives 

CondaIOError: IO error: Missing write permissions in: /anaconda3
#
# You don't appear to have the necessary permissions to install packages
# into the install area '/anaconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone=/anaconda3

How to fix it? I don't have permissions to install packages. Thanks.

**Comment by linwang6** [comment] 2018-09-25 22:41
Hi gioelelm,
When I try 'conda install numpy scipy cython numba matplotlib scikit-learn h5py click', 
it gives:
CondaIOError: IO error: Missing write permissions in: /anaconda3
## You don't appear to have the necessary permissions to install packages
# into the install area '/anaconda3'.
# However you can clone this environment into your home directory and# then make changes to it.
# This may be done using the command:
## $ conda create -n my_root --clone=/anaconda3

How to fix it? I don't have permissions to install packages. Thanks.

**Comment by linwang6** [comment] 2018-09-25 22:41
Hi gioelelm,
When I try 'conda install numpy scipy cython numba matplotlib scikit-learn h5py click', 
it gives:
CondaIOError: IO error: Missing write permissions in: /anaconda3
## You don't appear to have the necessary permissions to install packages
# into the install area '/anaconda3'.
# However you can clone this environment into your home directory and# then make changes to it.
# This may be done using the command:
## $ conda create -n my_root --clone=/anaconda3

How to fix it? I don't have permissions to install packages. Thanks.

**Comment by linwang6** [comment] 2018-09-25 22:48
Hi gioelelm,
When I try 'conda install numpy scipy cython numba matplotlib scikit-learn h5py click', 
it gives:
CondaIOError: IO error: Missing write permissions in: /anaconda3
You don't appear to have the necessary permissions to install packages
into the install area '/anaconda3'.
However you can clone this environment into your home directory and
then make changes to it.
This may be done using the command:
$ conda create -n my_root --clone=/anaconda3

How to fix it? I don't have permissions to install packages. Thanks.

**Comment by gioelelm** [comment] 2018-09-26 06:46
Make a new conda installation form scratch locally in your home folder.

**Comment by linwang6** [comment] 2018-09-26 22:31
Thanks!

**Comment by linwang6** [comment] 2018-09-27 06:52
When I try to use the anaconda3 to install velocyto, after installed, I got these errors,

MBP-2:/Users/anaconda3/bin$ velocyto 

anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/anaconda3/bin/velocyto", line 7, in <module>
    from velocyto.commands.velocyto import cli
  File "/Users/anaconda3/lib/python3.6/site-packages/velocyto/__init__.py", line 13, in <module>
    from .estimation import fit_slope, _fit1_slope, clusters_stats
  File "/Users/anaconda3/lib/python3.6/site-packages/velocyto/estimation.py", line 7, in <module>
    from .speedboosted import _colDeltaCor, _colDeltaCorLog10, _colDeltaCorSqrt
ImportError: dlopen(/Users/anaconda3/lib/python3.6/site-packages/velocyto/speedboosted.cpython-36m-darwin.so, 2): Symbol not found: _GOMP_parallel
  Referenced from: /Users/anaconda3/lib/python3.6/site-packages/velocyto/speedboosted.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/anaconda3/lib/python3.6/site-packages/velocyto/speedboosted.cpython-36m-darwin.so


How to fix it? Thanks.

**Comment by linwang6** [comment] 2018-09-27 19:07
> Yes exactly. Because of the dependencies on numpy, scipy, cython and a cythonized module that needs to be compiled, many problems might arise if any of them is not working 100%. The use of conda guarantees that you have a working installation comparable to the one I was using when developing the library.

Hi gioelelm,
Thanks so much for your response and help.
I reinstalled the velocyto following the installation guide (http://velocyto.org/velocyto.py/install/index.html), and I'm using conda on the cluster. It still not work on the cluster, could you give some advices for this?  Thanks.

PS: how much memory does velocyto need for 5000 cells? I'm thinking if it's the memory problem. Thanks.

**Closed** 2018-10-02 06:33 UTC
