### ISSUE TITLE
Memory requirements for 35000 cells (or more) and how to reduce them

### ISSUE THREAD

**Issue by Clara22** [velocyto-team/velocyto.py#165] opened 2018-12-21 11:23 UTC
Hello,

I am trying to run velocyto.py on the 10X aggregated output of 4 samples (>35.000 cells). I requested 400GB of memory and my job reached the memory limit after about 14h running. Is that expected for this number of cells? Is there anything I could do so that it requires less memory?

I will also mention that eventually I would like to run a 20 sample dataset of >140.000 cells.

Thanks in advance

Clara

**Comment by lambdamoses** [comment] 2019-01-08 21:32
I have the same problem. I have a dataset with about 14000 cells, and after running for about 14 hours, when the terminal is printing something like "counting for batch x, containing 100 cells", velocyto took up over 700 GB of memory, causing our server to run out of memory, killing the process. This is what I got from `dmesg`:

```
[911231.442637] Out of memory: Kill process 439141 (velocyto) score 881 or sacrifice child
[911231.442641] Killed process 439141 (velocyto) total-vm:35346339964kB, anon-rss:681575216kB, file-rss:812kB, shmem-rss:0kB
```

**Comment by gioelelm** [comment] 2019-01-08 22:12
Have you checked the other similar (solved) issues where I suggest several possible causes of this kind of errors? Usually this memory problems are caused by an incorrect argument passing. Most likely you are running the command line tool without a valid barcode list, this joined in a mildly dirty sample (with a lot of barcodes with a couple of reads) will cause the allocation of an expression table with hundreds of thousands of columns . Sent from my mobile - excuse the typos

**Comment by gioelelm** [comment] 2019-01-09 02:34
Also are you sure that gff3 the same as gtf? I thought gtf was something like gff v2.2. I support only gtf formatted files. Sent from my mobile - excuse the typos

**Comment by lambdamoses** [comment] 2019-01-09 02:46
According to the samtools documentation, the merged bam file should be sorted, so I did not explicitly sort the merged bam file. The gff3 file was generated by removing the "exon_number" field from the original gtf file. Here's what samtools documentation says about the merge command:

>Merge multiple sorted alignment files, producing a single sorted output file that contains all the input records and maintains the existing sort order.

I just realized from this issue: https://github.com/velocyto-team/velocyto.py/issues/115 that I should still sort the bam file with `-t CB` to generate the cell sorted bam file. I just generated that file and I'll see how velocyto goes.

**Comment by lambdamoses** [comment] 2019-01-10 00:49
This time I first sorted the merged bam file with samtools by position, and then sorted that file again with `-t CB` in samtools. Then the memory issue was resolved, and I successfully generated the loom file.

**Comment by Clara22** [comment] 2019-01-11 10:46
Same thing for me, I was missing the -t CB when doing samtools sort. It still takes hours but the memory requirements are much lower.

Thanks!

**Closed** 2019-01-15 14:59 UTC

**Comment by whitleyo** [comment] 2019-06-26 19:29
Hi, if it's the case that bams sorted by cell barcode then by position, should the documentation for the CLI be updated to reflect this?

http://velocyto.org/velocyto.py/tutorial/cli.html#run-run-on-any-technique-advanced-use

**Comment by whitleyo** [comment] 2019-06-28 14:36
Disregard, it appears that this has already been done
http://velocyto.org/velocyto.py/tutorial/cli.html#requirements-on-the-input-files

**Comment by denvercal1234GitHub** [comment] 2021-11-15 20:23
@lambdamoses - Would you mind posting how you did the sorting with samtools for your run10x please? Thank you so much.
