### ISSUE TITLE
High Memory usage of extract_intervals

### ISSUE THREAD

**Issue by gmstanle** [velocyto-team/velocyto.py#30] opened 2017-12-03 05:36 UTC
I am running extract_intervals on an mm10 annotation (from ENCODE but with the transcript_name field added at the end to solve that issue). It has 23337 genes and 30455 transcripts. It seems to take tons of memory - using up all the 64 gigs of ram I have and then eating into swap space, which obviously makes it run very slow - 20’ to process the first 2500 genes. 

How much memory use is expected for the extract_intervals program? I assume there is a problem somewhere here.

**Comment by gmstanle** [comment] 2017-12-03 05:54
It does appear to be annotation-specific. Extract_intervals seems to work fine with an Ensemble .gtf annotation that I just downloaded.

**Comment by gioelelm** [comment] 2017-12-03 06:58
I will look into this. Could you specify wich one was the gtf file that was leading to the bug?

**Comment by gmstanle** [comment] 2017-12-03 19:12
To be honest, I don't remember where I downloaded it - it was a while ago. But I can upload a subset of the entries (head -100 and tail -100) as a .txt file if that helps.
[mm10_trName_short.txt](https://github.com/velocyto-team/velocyto.py/files/1525069/mm10_trName_short.txt)

**Comment by gioelelm** [comment] 2017-12-03 19:19
I might have a clue what the problem is. I think it will be fixed in the new upcoming release.

You will have to wait about a week.

**Comment by gmstanle** [comment] 2017-12-03 19:52
Ok, thanks! By the way, in the mm10 .gtf, I had made the transcript_name identical to transcript_id (that was the easiest way to add a transcript_name field to the .gtf). So that may be problematic as well.

**Closed** 2018-01-23 11:25 UTC
